spring:
  datasource:
    url: jdbc:mysql://corporateproject-mysql.cd0yoy806w7s.ap-south-1.rds.amazonaws.com:3306/CorporateProject_db
    username: admin
    password: Test@123!
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 30000  # Adjust timeout if needed
      max-lifetime: 1800000

jpa:
    hibernate:
      ddl-auto: update  # Or validate or create if needed
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect  # Add this line
